title: Guia de Contribuição Para a Documentação do Kubernetes em Português
description: Guia de Contribuição Para a Documentação do Kubernetes em Português
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
